create table if not exists public.cotizaciones (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  cliente_id uuid not null references public.clientes(id) on delete restrict,
  numero bigint generated by default as identity,
  fecha date not null default current_date,
  vencimiento date,
  estado text not null default 'borrador' check (estado in ('borrador', 'enviada', 'aprobada')),
  subtotal numeric(12, 2) not null default 0,
  iva numeric(12, 2) not null default 0,
  total numeric(12, 2) not null default 0,
  notas text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cotizacion_items (
  id uuid primary key default gen_random_uuid(),
  cotizacion_id uuid not null references public.cotizaciones(id) on delete cascade,
  descripcion text not null,
  cantidad numeric(12, 2) not null check (cantidad > 0),
  precio_unitario numeric(12, 2) not null check (precio_unitario >= 0),
  total numeric(12, 2) not null check (total >= 0),
  created_at timestamptz not null default now()
);

create index if not exists cotizaciones_empresa_id_idx on public.cotizaciones (empresa_id);
create index if not exists cotizaciones_cliente_id_idx on public.cotizaciones (cliente_id);
create index if not exists cotizacion_items_cotizacion_id_idx on public.cotizacion_items (cotizacion_id);

alter table public.cotizaciones enable row level security;
alter table public.cotizacion_items enable row level security;

create policy "usuarios ven cotizaciones de su empresa"
on public.cotizaciones
for select
to authenticated
using (empresa_id = public.usuario_empresa_id());

create policy "usuarios crean cotizaciones de su empresa"
on public.cotizaciones
for insert
to authenticated
with check (empresa_id = public.usuario_empresa_id());

create policy "usuarios actualizan cotizaciones de su empresa"
on public.cotizaciones
for update
to authenticated
using (empresa_id = public.usuario_empresa_id())
with check (empresa_id = public.usuario_empresa_id());

create policy "usuarios eliminan cotizaciones de su empresa"
on public.cotizaciones
for delete
to authenticated
using (empresa_id = public.usuario_empresa_id());

create policy "usuarios ven items de cotizaciones de su empresa"
on public.cotizacion_items
for select
to authenticated
using (
  exists (
    select 1
    from public.cotizaciones
    where cotizaciones.id = cotizacion_items.cotizacion_id
      and cotizaciones.empresa_id = public.usuario_empresa_id()
  )
);

create policy "usuarios crean items de cotizaciones de su empresa"
on public.cotizacion_items
for insert
to authenticated
with check (
  exists (
    select 1
    from public.cotizaciones
    where cotizaciones.id = cotizacion_items.cotizacion_id
      and cotizaciones.empresa_id = public.usuario_empresa_id()
  )
);

create policy "usuarios actualizan items de cotizaciones de su empresa"
on public.cotizacion_items
for update
to authenticated
using (
  exists (
    select 1
    from public.cotizaciones
    where cotizaciones.id = cotizacion_items.cotizacion_id
      and cotizaciones.empresa_id = public.usuario_empresa_id()
  )
)
with check (
  exists (
    select 1
    from public.cotizaciones
    where cotizaciones.id = cotizacion_items.cotizacion_id
      and cotizaciones.empresa_id = public.usuario_empresa_id()
  )
);

create policy "usuarios eliminan items de cotizaciones de su empresa"
on public.cotizacion_items
for delete
to authenticated
using (
  exists (
    select 1
    from public.cotizaciones
    where cotizaciones.id = cotizacion_items.cotizacion_id
      and cotizaciones.empresa_id = public.usuario_empresa_id()
  )
);
